### ISSUE TITLE
TBB/OpenCL Includes

### ISSUE THREAD

**Issue by cianyleow** [HPCE/hpce-2015-cw5#4]
Where will the TBB/OpenCL includes be on the AWS instance? Or should we include them in our include/ folder?

**Comment by m8pple** [comment]
I think what I'll do is to check the AMI so that TBB/OpenCL includes are in a known
location (and updated if nesc.), then state where they will be located in the spec.

I don't really want people's repos getting too bloated with SDKs, as it's encouraging
poor development practise (the way I did CW4 was already a bit iffy).

I'll look at it later tonight, as updating the AMI can take a bit of time.

**Comment by m8pple** [comment]
Hrmm, took a bit more time than it should have done. The spec has now been updated
to point at a specific AMI, which contains both OpenCL providers and the TBB libraries.
