### ISSUE TITLE
Seg Fault with enqueueBarrierWithWaitList

### ISSUE THREAD

**Issue by cianyleow** [HPCE/hpce-2015-cw5#6]
@m8pple When I try to run our programs on an AWS instance with a newer version of OpenCL (v1.2 I believe), it requires that we use enqueueBarrierWithWaitList() which is causing segmentation faults with NULL values for *event_wait_list and *event. Any ideas on how to fix this? I was going to try and fix it by creating dummy values for *event_wait_list and *event, but that seems unnecessary.

**Comment by m8pple** [comment]
Hrmm, odd. I haven't noticed that before.

Can you tell whether the crash is happening due to something that cl.hpp is doing, or is it happening
within the underlying opencl library? It might be worth attaching a debugger to see exactly which
part is causing the problem.

If it's something in cl.hpp, you could try calling clEnqueueBarrierWithWaitList directly, rather than
through the API. I think that given a queue called `queue`, you can get the underlying handle
using `queue()`, then pass that to the function.

Another question is whether it crashes on all implementations. Does the software work while the
GPU doesn't? (It might be a driver bug).

You could also remove the barrier, and indicated dependencies directly using events.

**Comment by m8pple** [comment]
I had a look into this while doing the last run. I'm pretty sure that it is not
a problem with enqueueBarrierWithWaitList, it's just that when you call
that function is when it happens to encounter an error. Even if you remove
the call to barrier, it still crashes. Using a software provider results in
some progress, but then a crash in a non-deterministic place.

My strong suspicion is memory corruption, usually caused by writing
outside a buffer. Places I would look are:
- Copying data to/from the GPU. In particular, are the destinations
  (either host of GPU) of the right size.
- Writing to data from within the kernel. Are they staying within the kernel?

In terms of the life kernel, you might refer to section 6.8.k of the OpenCL 1.1
spec, and see what it says about bools.

**Comment by cianyleow** [comment]
Having run this with the old OpenCL include that you provided from issue
#1, it seems fine now... Not sure if we're still running into issues with
the writing outside buffers anymore, it's not an issue with an older
version of OpenCL or that it's something else that we don't know about...

It could be because we coded it up on an old version of OpenCL 1.1 and are
now porting it on to OpenCL 1.2 and there's some differences we haven't
accounted for. Either way, using the include/CL/cl.hpp include makes it
work, so I'm going to leave it alone for now as we're quite close to
submission... Will look up the bools thing with Jake though.
